const UserActionTypes = {
    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE : 'SIGN_UP_FAILURE',
    LOGIN_START : 'LOGIN_START',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    VERIFY_TOKEN_START : 'VERIFY_TOKEN_START',
    VERIFY_TOKEN_SUCCESS : 'VERIFY_TOKEN_SUCCESS',
    VERiFY_TOKEN_ERROR : 'VERIFY_TOKEN_ERROR',
    LOGOUT_START : 'LOGOUT_START'
};


export default UserActionTypes;